# Generated by Django 5.2.5 on 2025-08-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
